package main

import "time"

func recoverSeekMSFromSnapshot(previousSeekMS int64, previousSeekUpdatedAt, now time.Time) int64 {
	if previousSeekMS < 0 {
		previousSeekMS = 0
	}
	if previousSeekUpdatedAt.IsZero() {
		return previousSeekMS
	}
	delta := now.Sub(previousSeekUpdatedAt).Milliseconds()
	if delta < 0 {
		delta = 0
	}
	return previousSeekMS + delta
}

func normalizedDurationPessimism(durationPessimism float64) float64 {
	if durationPessimism <= 0 || durationPessimism > 1 {
		return 0.75
	}
	return durationPessimism
}

func restoreThresholdMS(knownDurationMS int, durationPessimism float64) int64 {
	if knownDurationMS <= 0 {
		return 0
	}
	return int64(float64(knownDurationMS) * normalizedDurationPessimism(durationPessimism))
}

func elapsedPercentOfDuration(preBoundaryElapsedMS int64, knownDurationMS int) float64 {
	if preBoundaryElapsedMS <= 0 || knownDurationMS <= 0 {
		return 0
	}
	return (float64(preBoundaryElapsedMS) / float64(knownDurationMS)) * 100
}

func shouldRestorePreBoundaryResult(isHardBoundaryTrigger bool, preBoundarySeekMS int64, preBoundaryElapsedMS int64, knownDurationMS int, minSeekForRestore time.Duration, durationPessimism float64) (bool, string) {
	if minSeekForRestore <= 0 {
		minSeekForRestore = 60 * time.Second
	}
	durationPessimism = normalizedDurationPessimism(durationPessimism)
	if !isHardBoundaryTrigger {
		// Soft boundaries are usually generated by low-energy passages or seamless
		// transitions. If the recognizer reconfirms the same track, always restore
		// the pre-boundary snapshot to keep progress monotonic.
		return true, ""
	}
	if knownDurationMS > 0 {
		suppressUntil := restoreThresholdMS(knownDurationMS, durationPessimism)
		if preBoundaryElapsedMS > 0 && preBoundaryElapsedMS < suppressUntil {
			return true, ""
		}
	}
	if preBoundarySeekMS < minSeekForRestore.Milliseconds() {
		return false, "seek too short"
	}
	return false, "hard boundary"
}
