#!/bin/bash
set -e

case "$1" in
    purge)
        rm -rf /etc/oceano
        rm -rf /var/lib/oceano
        rm -rf /opt/oceano-venv
        rm -rf /usr/local/lib/oceano
        systemctl daemon-reload
        ;;

    remove|upgrade|disappear|abort-install|abort-upgrade)
        systemctl daemon-reload
        ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

exit 0
